### ISSUE TITLE
Power Management Broken

### ISSUE THREAD

**Issue by JoshMayBalGitHub** [Polunom/mac-inline-battery#5]
**KDE Plasma**: 5.24.4
**KDE Frameworks:** 5.92.0
**Qt:** 5.15.2
Using **Latte 0.10.76**

After updating my KDE desktop environment, i tried to use the power management thing at the battery but it says this error:
![Screenshot_20220405_014606](https://user-images.githubusercontent.com/93077235/161601962-e751cdb8-50e1-4004-a0b4-ab8fcf6fe7f3.png)

I know that the power management itself is not broken because:
![Screenshot_20220405_014955](https://user-images.githubusercontent.com/93077235/161602118-da7da182-0bce-495e-93f4-a5c8eab87a9c.png)

Its likely because mac-inline-battery doesnt support it, but please update it. I have to go to system settings instead of clicking on the battery icon.

_Edit:_ Oh and uh i tried some solutions to the error itself but none of them worked for me

_Edit 2:_ I ""fixed"" it by using the default battery and then using the[ battery time plasmoid ](https://store.kde.org/p/1166501)to look like inline battery:
![Screenshot_20220405_105307](https://user-images.githubusercontent.com/93077235/161669613-b2abdf76-b41d-4b7f-8c9b-79687b835b26.png)
but it doesnt look right but its the best ""fix"" that i made. but still, please fix

**Comment by IOplus** [comment]
I'm also having the same issue, any updates on this?

**Comment by 0kzh** [comment]
Hey sorry but I no longer use Linux so I have no way to continue maintaining this plugin. Feel free to submit a PR for this feature though!
