### ISSUE TITLE
It shows 100% battery when battery is actually 0%.

### ISSUE THREAD

**Issue by SATYADAHAL** [Polunom/mac-inline-battery#6]
When the charge reaches 0% it actually shows that the charge to be 100%. It really confuses me. And the red color indicator is also gone as there 

Some info about by system.
1. I am running fedora KDE spin.
2. KDE Plasma Version: 5.25.5
3. Qt Version: 5.15.5
4. Kernel Version: 5.19.11
5. Graphics Platform: X11

**Comment by SATYADAHAL** [comment]
![notcharging_battery](https://user-images.githubusercontent.com/51309409/192666583-bb396ad5-db36-452f-8136-62955c7ac62f.png)

**Comment by 0kzh** [comment]
Hey, sorry but I'm no longer running a Linux distro to debug this. Feel free to push a fix if you find the issue though!
